# ============================
# Ensure correct Java environment for OpenJDK 11
# ============================

# Add OpenJDK 11 to PATH
export PATH="/opt/homebrew/opt/openjdk@11/bin:$PATH"
# Set JAVA_HOME to OpenJDK 11
export JAVA_HOME="$(brew --prefix openjdk@11)/libexec/openjdk.jdk/Contents/Home"
# Add JAVA_HOME/bin to PATH
export PATH="$JAVA_HOME/bin:$PATH"

# If you would rather use your system default Java (e.g., Apple's),
# uncomment the following line to overwrite the above JAVA_HOME:
# export JAVA_HOME=$(/usr/libexec/java_home)

# ============================
# Conda setup (auto-generated by 'conda init')
# ============================
__conda_setup="$('/opt/homebrew/Caskroom/miniconda/base/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/opt/homebrew/Caskroom/miniconda/base/etc/profile.d/conda.sh" ]; then
        # . "/opt/homebrew/Caskroom/miniconda/base/etc/profile.d/conda.sh"  # commented out by conda initialize
        # Uncomment the line above if you prefer this approach for loading conda.
    else
        export PATH="/opt/homebrew/Caskroom/miniconda/base/bin:$PATH"
    fi
fi
unset __conda_setup

